/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
package com.ludei.chromium;

public final class R {
	public static final class attr {
		public static final int chromiumDropdownListPreferredItemHeight = 0x7f010002;
		public static final int webviewchromium_select_dialog_multichoice = 0x7f010000;
		public static final int webviewchromium_select_dialog_singlechoice = 0x7f010001;
	}
	public static final class bool {
		public static final int lockscreen_isPortrait = 0x7f090000;
	}
	public static final class color {
		public static final int webviewchromium_color_picker_border_color = 0x7f060000;
	}
	public static final class dimen {
		public static final int webviewchromium_color_picker_gradient_margin = 0x7f070001;
		public static final int webviewchromium_link_preview_overlay_radius = 0x7f070000;
	}
	public static final class drawable {
		public static final int ic_media_video_poster = 0x7f020000;
		public static final int resource_icon = 0x7f020002;
		public static final int webviewchromium_autofill_popup_background = 0x7f020004;
		public static final int webviewchromium_autofill_popup_background_down = 0x7f020005;
		public static final int webviewchromium_autofill_popup_background_up = 0x7f020006;
		public static final int webviewchromium_color_picker_advanced_select_handle = 0x7f020007;
		public static final int webviewchromium_color_picker_border = 0x7f020008;
		public static final int webviewchromium_ondemand_overlay = 0x7f020009;
	}
	public static final class id {
		public static final int message = 0x7f0a0001;
		public static final int selected_color_view_border = 0x7f0a0011;
		public static final int value = 0x7f0a0002;
		public static final int webview_chromium_color_picker_gradient_border = 0x7f0a0007;
		public static final int webviewchromium_autofill_label = 0x7f0a0004;
		public static final int webviewchromium_autofill_menu_text = 0x7f0a0003;
		public static final int webviewchromium_autofill_popup_window = 0x7f0a0000;
		public static final int webviewchromium_autofill_sublabel = 0x7f0a0005;
		public static final int webviewchromium_color_picker_advanced = 0x7f0a000a;
		public static final int webviewchromium_color_picker_gradient = 0x7f0a0008;
		public static final int webviewchromium_color_picker_more_colors_button = 0x7f0a000e;
		public static final int webviewchromium_color_picker_more_colors_button_border = 0x7f0a000d;
		public static final int webviewchromium_color_picker_seek_bar = 0x7f0a0009;
		public static final int webviewchromium_color_picker_selected_color_view = 0x7f0a0012;
		public static final int webviewchromium_color_picker_selected_color_view_border = 0x7f0a0010;
		public static final int webviewchromium_color_picker_simple = 0x7f0a000c;
		public static final int webviewchromium_color_picker_simple_border = 0x7f0a000b;
		public static final int webviewchromium_color_picker_text = 0x7f0a0006;
		public static final int webviewchromium_color_picker_title = 0x7f0a000f;
		public static final int webviewchromium_date_picker = 0x7f0a0013;
		public static final int webviewchromium_pickers = 0x7f0a0015;
		public static final int webviewchromium_position_in_year = 0x7f0a0016;
		public static final int webviewchromium_select_action_menu_copy = 0x7f0a001a;
		public static final int webviewchromium_select_action_menu_cut = 0x7f0a0019;
		public static final int webviewchromium_select_action_menu_paste = 0x7f0a001b;
		public static final int webviewchromium_select_action_menu_select_all = 0x7f0a0018;
		public static final int webviewchromium_select_action_menu_share = 0x7f0a001c;
		public static final int webviewchromium_select_action_menu_web_search = 0x7f0a001d;
		public static final int webviewchromium_time_picker = 0x7f0a0014;
		public static final int webviewchromium_year = 0x7f0a0017;
	}
	public static final class layout {
		public static final int js_prompt = 0x7f030000;
		public static final int webview_select_singlechoice = 0x7f030001;
		public static final int webviewchromium_autofill_text = 0x7f030002;
		public static final int webviewchromium_color_picker_advanced_component = 0x7f030003;
		public static final int webviewchromium_color_picker_dialog_content = 0x7f030004;
		public static final int webviewchromium_color_picker_dialog_title = 0x7f030005;
		public static final int webviewchromium_date_time_picker_dialog = 0x7f030006;
		public static final int webviewchromium_two_field_date_picker = 0x7f030007;
	}
	public static final class menu {
		public static final int webviewchromium_select_action_menu = 0x7f0c0000;
	}
	public static final class raw {
		public static final int blank_html = 0x7f050000;
		public static final int loaderror = 0x7f050001;
		public static final int nodomain = 0x7f050002;
		public static final int resource_file = 0x7f050003;
		public static final int resource_icon = 0x7f050004;
	}
	public static final class string {
		public static final int cancel = 0x7f080028;
		public static final int default_text_encoding = 0x7f080000;
		public static final int icu_abbrev_wday_month_day_no_year = 0x7f080002;
		public static final int js_dialog_before_unload = 0x7f080026;
		public static final int js_dialog_before_unload_negative_button = 0x7f080025;
		public static final int js_dialog_before_unload_positive_button = 0x7f080024;
		public static final int js_dialog_before_unload_title = 0x7f080023;
		public static final int js_dialog_title = 0x7f080021;
		public static final int js_dialog_title_default = 0x7f080022;
		public static final int lock_pattern_view_aspect = 0x7f080001;
		public static final int ok = 0x7f080027;
		public static final int share = 0x7f080029;
		public static final int system_ui_date_pattern = 0x7f080003;
		public static final int websearch = 0x7f08002a;
		public static final int webviewchromium_accessibility_content_view = 0x7f080006;
		public static final int webviewchromium_accessibility_date_picker_month = 0x7f08000f;
		public static final int webviewchromium_accessibility_date_picker_week = 0x7f080010;
		public static final int webviewchromium_accessibility_date_picker_year = 0x7f080011;
		public static final int webviewchromium_accessibility_datetime_picker_date = 0x7f08000d;
		public static final int webviewchromium_accessibility_datetime_picker_time = 0x7f08000e;
		public static final int webviewchromium_actionbar_share = 0x7f080004;
		public static final int webviewchromium_actionbar_web_search = 0x7f080005;
		public static final int webviewchromium_color_picker_button_cancel = 0x7f08001c;
		public static final int webviewchromium_color_picker_button_more = 0x7f080017;
		public static final int webviewchromium_color_picker_button_set = 0x7f08001b;
		public static final int webviewchromium_color_picker_dialog_title = 0x7f08001d;
		public static final int webviewchromium_color_picker_hue = 0x7f080018;
		public static final int webviewchromium_color_picker_saturation = 0x7f080019;
		public static final int webviewchromium_color_picker_value = 0x7f08001a;
		public static final int webviewchromium_date_picker_dialog_clear = 0x7f080008;
		public static final int webviewchromium_date_picker_dialog_set = 0x7f080007;
		public static final int webviewchromium_date_picker_dialog_title = 0x7f080009;
		public static final int webviewchromium_date_time_picker_dialog_title = 0x7f08000a;
		public static final int webviewchromium_low_memory_error = 0x7f08001e;
		public static final int webviewchromium_media_player_error_button = 0x7f080015;
		public static final int webviewchromium_media_player_error_text_invalid_progressive_playback = 0x7f080013;
		public static final int webviewchromium_media_player_error_text_unknown = 0x7f080014;
		public static final int webviewchromium_media_player_error_title = 0x7f080012;
		public static final int webviewchromium_media_player_loading_video = 0x7f080016;
		public static final int webviewchromium_month_picker_dialog_title = 0x7f08000b;
		public static final int webviewchromium_opening_file_error = 0x7f08001f;
		public static final int webviewchromium_private_browsing_warning = 0x7f080020;
		public static final int webviewchromium_week_picker_dialog_title = 0x7f08000c;
	}
	public static final class style {
		public static final int webviewchromium_AutofillPopupWindow = 0x7f0b0000;
		public static final int webviewchromium_SelectPopupDialog = 0x7f0b0001;
	}
}
