/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.apache.cordova;

public final class R {
    public static final class attr {
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int chromiumDropdownListPreferredItemHeight=0x7f010002;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int webviewchromium_select_dialog_multichoice=0x7f010000;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int webviewchromium_select_dialog_singlechoice=0x7f010001;
    }
    public static final class bool {
        /**  @hide DO NOT TRANSLATE. Workaround for resource race condition in lockscreen. 
         */
        public static int lockscreen_isPortrait=0x7f080000;
    }
    public static final class color {
        public static int webviewchromium_color_picker_border_color=0x7f050000;
    }
    public static final class dimen {
        /** 
        14.5 = Seekbar thumb width - border width, but it depends on the width
            of the seek bar icon.
    
         */
        public static int webviewchromium_color_picker_gradient_margin=0x7f060001;
        /**  Link Preview dimensions 
         */
        public static int webviewchromium_link_preview_overlay_radius=0x7f060000;
    }
    public static final class drawable {
        public static int ic_media_video_poster=0x7f020000;
        public static int resource_icon=0x7f020001;
        public static int webviewchromium_autofill_popup_background=0x7f020002;
        public static int webviewchromium_autofill_popup_background_down=0x7f020003;
        public static int webviewchromium_autofill_popup_background_up=0x7f020004;
        public static int webviewchromium_color_picker_advanced_select_handle=0x7f020005;
        public static int webviewchromium_color_picker_border=0x7f020006;
        public static int webviewchromium_ondemand_overlay=0x7f020007;
    }
    public static final class id {
        public static int message=0x7f090001;
        public static int selected_color_view_border=0x7f090011;
        public static int value=0x7f090002;
        public static int webview_chromium_color_picker_gradient_border=0x7f090007;
        public static int webviewchromium_autofill_label=0x7f090004;
        public static int webviewchromium_autofill_menu_text=0x7f090003;
        public static int webviewchromium_autofill_popup_window=0x7f090000;
        public static int webviewchromium_autofill_sublabel=0x7f090005;
        public static int webviewchromium_color_picker_advanced=0x7f09000a;
        public static int webviewchromium_color_picker_gradient=0x7f090008;
        public static int webviewchromium_color_picker_more_colors_button=0x7f09000e;
        public static int webviewchromium_color_picker_more_colors_button_border=0x7f09000d;
        public static int webviewchromium_color_picker_seek_bar=0x7f090009;
        public static int webviewchromium_color_picker_selected_color_view=0x7f090012;
        public static int webviewchromium_color_picker_selected_color_view_border=0x7f090010;
        public static int webviewchromium_color_picker_simple=0x7f09000c;
        public static int webviewchromium_color_picker_simple_border=0x7f09000b;
        public static int webviewchromium_color_picker_text=0x7f090006;
        public static int webviewchromium_color_picker_title=0x7f09000f;
        public static int webviewchromium_date_picker=0x7f090013;
        public static int webviewchromium_pickers=0x7f090015;
        public static int webviewchromium_position_in_year=0x7f090016;
        public static int webviewchromium_select_action_menu_copy=0x7f09001a;
        public static int webviewchromium_select_action_menu_cut=0x7f090019;
        public static int webviewchromium_select_action_menu_paste=0x7f09001b;
        public static int webviewchromium_select_action_menu_select_all=0x7f090018;
        public static int webviewchromium_select_action_menu_share=0x7f09001c;
        public static int webviewchromium_select_action_menu_web_search=0x7f09001d;
        public static int webviewchromium_time_picker=0x7f090014;
        public static int webviewchromium_year=0x7f090017;
    }
    public static final class layout {
        public static int js_prompt=0x7f030000;
        public static int webview_select_singlechoice=0x7f030001;
        public static int webviewchromium_autofill_text=0x7f030002;
        public static int webviewchromium_color_picker_advanced_component=0x7f030003;
        public static int webviewchromium_color_picker_dialog_content=0x7f030004;
        public static int webviewchromium_color_picker_dialog_title=0x7f030005;
        public static int webviewchromium_date_time_picker_dialog=0x7f030006;
        public static int webviewchromium_two_field_date_picker=0x7f030007;
    }
    public static final class menu {
        public static int webviewchromium_select_action_menu=0x7f0b0000;
    }
    public static final class raw {
        public static int blank_html=0x7f040000;
        public static int loaderror=0x7f040001;
        public static int nodomain=0x7f040002;
        public static int resource_file=0x7f040003;
        public static int resource_icon=0x7f040004;
    }
    public static final class string {
        public static int cancel=0x7f070028;
        /**  Default text encoding for WebSettings. 
         */
        public static int default_text_encoding=0x7f070000;
        /**  @hide DO NOT TRANSLATE. ICU pattern for "Mon, 14 January" 
         */
        public static int icu_abbrev_wday_month_day_no_year=0x7f070002;
        public static int js_dialog_before_unload=0x7f070026;
        public static int js_dialog_before_unload_negative_button=0x7f070025;
        public static int js_dialog_before_unload_positive_button=0x7f070024;
        public static int js_dialog_before_unload_title=0x7f070023;
        public static int js_dialog_title=0x7f070021;
        public static int js_dialog_title_default=0x7f070022;
        /**  @hide DO NOT TRANSLATE. Control aspect ratio of lock pattern 
         */
        public static int lock_pattern_view_aspect=0x7f070001;
        public static int ok=0x7f070027;
        public static int share=0x7f070029;
        /**  @hide DO NOT TRANSLATE. date formatting pattern for system ui.
         */
        public static int system_ui_date_pattern=0x7f070003;
        public static int websearch=0x7f07002a;
        /**  Content description for the content view that holds the web contents [CHAR-LIMIT=32] 
         */
        public static int webviewchromium_accessibility_content_view=0x7f070006;
        /**  Content description for the date time picker month component. [CHAR-LIMIT=32] 
         */
        public static int webviewchromium_accessibility_date_picker_month=0x7f07000f;
        /**  Content description for the date time picker week component. [CHAR-LIMIT=32] 
         */
        public static int webviewchromium_accessibility_date_picker_week=0x7f070010;
        /**  Content description for the date time picker year component. [CHAR-LIMIT=32] 
         */
        public static int webviewchromium_accessibility_date_picker_year=0x7f070011;
        /**  Content description for the date time picker date component. [CHAR-LIMIT=32] 
         */
        public static int webviewchromium_accessibility_datetime_picker_date=0x7f07000d;
        /**  Content description for the date time picker time component. [CHAR-LIMIT=32] 
         */
        public static int webviewchromium_accessibility_datetime_picker_time=0x7f07000e;
        /**  Contextual action bar item for sharing a block of text via email, or
         other method. [CHAR-LIMIT=24] 
         */
        public static int webviewchromium_actionbar_share=0x7f070004;
        /**  Contextual action bar item for using the selected text in a internet
         search. [CHAR-LIMIT=24] 
         */
        public static int webviewchromium_actionbar_web_search=0x7f070005;
        /**  Label for button in Color Picker dialog for user to cancel picking a
         color. [CHAR-LIMIT=20] 
         */
        public static int webviewchromium_color_picker_button_cancel=0x7f07001c;
        /**  Text for Color Picker button to go to advanced view. [CHAR-LIMIT=20] 
         */
        public static int webviewchromium_color_picker_button_more=0x7f070017;
        /**  Label for button in Color Picker dialog for user to accept the currently
         chosen color. [CHAR-LIMIT=20] 
         */
        public static int webviewchromium_color_picker_button_set=0x7f07001b;
        /**  Title of Color Picker dialog. [CHAR-LIMIT=20] 
         */
        public static int webviewchromium_color_picker_dialog_title=0x7f07001d;
        /**  Label for hue slider in Color Picker. 
         */
        public static int webviewchromium_color_picker_hue=0x7f070018;
        /**  Label for saturation slider in Color Picker. 
         */
        public static int webviewchromium_color_picker_saturation=0x7f070019;
        /**  Label for value slider in Color Picker. 
         */
        public static int webviewchromium_color_picker_value=0x7f07001a;
        /**  Label for 'clear' button in date picker dialog, used to replace the contents of a field with the empty string [CHAR-LIMIT=12] 
         */
        public static int webviewchromium_date_picker_dialog_clear=0x7f070008;
        /**  Date/time picker dialog strings 
 Label for 'set' button in date picker dialog, used to replace the contents of a field with the chosen date [CHAR-LIMIT=12] 
         */
        public static int webviewchromium_date_picker_dialog_set=0x7f070007;
        /**  Title for the date picker dialog, which can be used to choose a date. [CHAR-LIMIT=32] 
         */
        public static int webviewchromium_date_picker_dialog_title=0x7f070009;
        /**  Title for the date/time picker dialog, which can be used to choose a date and time. [CHAR-LIMIT=32] 
         */
        public static int webviewchromium_date_time_picker_dialog_title=0x7f07000a;
        /**  Error shown when the browser is restarted due to low memory during a file picker operation. [CHAR-LIMIT=NONE] 
         */
        public static int webviewchromium_low_memory_error=0x7f07001e;
        /**  NO DESCRIPTION [CHAR-LIMIT=16] 
         */
        public static int webviewchromium_media_player_error_button=0x7f070015;
        /**  NO DESCRIPTION [CHAR-LIMIT=100] 
         */
        public static int webviewchromium_media_player_error_text_invalid_progressive_playback=0x7f070013;
        /**  NO DESCRIPTION [CHAR-LIMIT=100] 
         */
        public static int webviewchromium_media_player_error_text_unknown=0x7f070014;
        /**  Media player 
 NO DESCRIPTION [CHAR-LIMIT=32] 
         */
        public static int webviewchromium_media_player_error_title=0x7f070012;
        /**  NO DESCRIPTION [CHAR-LIMIT=20] 
         */
        public static int webviewchromium_media_player_loading_video=0x7f070016;
        /**  Title for the month picker dialog, which can be used to choose a month. [CHAR-LIMIT=32] 
         */
        public static int webviewchromium_month_picker_dialog_title=0x7f07000b;
        /** Toast when the browser is unable to open a file for upload. [CHAR-LIMIT=32] 
         */
        public static int webviewchromium_opening_file_error=0x7f07001f;
        /**  Warning shown when the app tries to create a private browsing WebView,
         which is not supported. [CHAR-LIMIT=NONE] 
         */
        public static int webviewchromium_private_browsing_warning=0x7f070020;
        /**  Title for the week picker dialog, which can be used to choose a week. [CHAR-LIMIT=32] 
         */
        public static int webviewchromium_week_picker_dialog_title=0x7f07000c;
    }
    public static final class style {
        public static int webviewchromium_AutofillPopupWindow=0x7f0a0000;
        public static int webviewchromium_SelectPopupDialog=0x7f0a0001;
    }
}
